#!/usr/bin/env python3
"""Build the single-file arcade application from ordered source fragments."""

from __future__ import annotations

import argparse
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parent.parent
SOURCE_DIR = ROOT / "arcade_src"
OUTPUT = ROOT / "arcade_app.py"
MANIFEST = (
    "00_runtime.py",
    "10_games_classic.py",
    "20_games_action.py",
    "30_demos.py",
    "40_games_simulation.py",
    "50_games_arcade.py",
    "60_games_extended.py",
    "70_games_classics.py",
    "80_games_original.py",
    "90_menus_and_main.py",
)
GENERATED_HEADER = (
    "# Generated from arcade_src/ by tools/build_arcade_bundle.py.\n"
    "# Edit the source fragments and run `make arcade-bundle`; do not edit this file.\n\n"
)


def build_bundle() -> str:
    """Return the deterministic bundle assembled in dependency order."""
    missing = [name for name in MANIFEST if not (SOURCE_DIR / name).is_file()]
    if missing:
        raise FileNotFoundError("missing arcade source fragments: " + ", ".join(missing))
    fragments = (
        (SOURCE_DIR / name).read_text(encoding="utf-8") for name in MANIFEST
    )
    return GENERATED_HEADER + "".join(fragments)


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail when arcade_app.py differs from the modular sources",
    )
    args = parser.parse_args()
    bundle = build_bundle()
    current = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else None

    if args.check:
        if current != bundle:
            print("arcade_app.py is stale; run `make arcade-bundle`", file=sys.stderr)
            return 1
        print("arcade_app.py matches arcade_src")
        return 0

    if current == bundle:
        print("arcade_app.py is already up to date")
    else:
        OUTPUT.write_text(bundle, encoding="utf-8")
        print("built arcade_app.py from", len(MANIFEST), "source fragments")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
